language: python
sudo: true
python:
  - "2.7"
env:
  - DJANGO_REQUIREMENT="Django>=1.7,<1.8"
  - DJANGO_REQUIREMENT="Django>=1.8,<1.9"
before_install:
  - sudo apt-get install build-essential libssl-dev libffi-dev python-dev -y
install:
  - pip install -q $DJANGO_REQUIREMENT django-mptt Pillow feedparser flake8
  - pip install -r requirements.txt --use-mirrors
  - pip install -r requirements/extras/horizon.txt
  - pip install -r requirements/extras/web.txt
  - python setup.py -q install
script: "cd tests && python manage.py test testapp"
after_success:
  - coveralls
branches:
  only:
    - master
    - develop
notifications:
  email:
    recipients:
    - mail@majklk.cz
    on_success: never
    on_failure: always