language: python
sudo: false
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
env:
  - DJANGO_REQUIREMENT="Django>=1.6,<1.7"
  - DJANGO_REQUIREMENT="Django>=1.7,<1.8"
  - DJANGO_REQUIREMENT="Django>=1.8,<1.9"
matrix:
  exclude:
    - python: "2.6"
      env: DJANGO_REQUIREMENT="Django>=1.7,<1.8"
    - python: "2.6"
      env: DJANGO_REQUIREMENT="Django>=1.8,<1.9"
install:
  - pip install -q $DJANGO_REQUIREMENT django-mptt Pillow feedparser flake8
  - pip install -r requirements.txt --use-mirrors
  - pip install -r requirements/extras/horizon.txt
  - pip install -r requirements/extras/web.txt
  - python setup.py -q install
script: "cd tests && python manage.py test testapp && flake8 ."
after_success:
  - coveralls
branches:
  only:
    - master
    - develop
notifications:
  email:
    recipients:
    - mail@majklk.cz
    on_success: never
    on_failure: always